### ISSUE TITLE
Game Crash when using portal

### ISSUE THREAD

**Issue by BlackFedora1019** [Nettakrim/Spyglass-Astronomy#32] opened 2024-06-26 22:46 UTC
Ive encountered an issue on my server, where when i go through a nether portal it completely crashes my game. I checked the crash logs and it said the issue came from this mod. Any idea as to why?
For context I am in fabric 1.20.1.
Here is the crash log:
`---- Minecraft Crash Report ----

// Don't be sad, have a hug! <3

 

Time: 2024-06-26 18:39:28

Description: Unexpected error

 

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_642.method_52811()'

	at com.nettakrim.spyglass_astronomy.SpaceDataManager.getCurrentWorldOrServerName(SpaceDataManager.java:261)

	at com.nettakrim.spyglass_astronomy.SpaceDataManager.<init>(SpaceDataManager.java:44)

	at com.nettakrim.spyglass_astronomy.SpyglassAstronomyClient.loadSpace(SpyglassAstronomyClient.java:104)

	at net.minecraft.class_310.handler$ekd000$spyglass_astronomy$loadSpace(class_310.java:23007)

	at net.minecraft.class_310.method_1481(class_310.java:2155)

	at net.minecraft.class_634.method_11117(class_634.java:1114)

	at net.minecraft.class_2724.method_11782(class_2724.java:78)

	at net.minecraft.class_2724.method_11054(class_2724.java:16)

	at net.minecraft.class_2600.method_11072(class_2600.java:22)

	at net.minecraft.class_1255.method_18859(class_1255.java:156)

	at net.minecraft.class_4093.method_18859(class_4093.java:23)

	at net.minecraft.class_1255.method_16075(class_1255.java:130)

	at net.minecraft.class_1255.method_5383(class_1255.java:115)

	at net.minecraft.class_310.method_1523(class_310.java:1175)

	at net.minecraft.class_310.method_1514(class_310.java:802)

	at net.minecraft.client.main.Main.main(Main.java:250)

	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)

	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)

	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

 

 

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

 

-- Head --

Thread: Render thread

Stacktrace:

	at com.nettakrim.spyglass_astronomy.SpaceDataManager.getCurrentWorldOrServerName(SpaceDataManager.java:261)

	at com.nettakrim.spyglass_astronomy.SpaceDataManager.<init>(SpaceDataManager.java:44)

	at com.nettakrim.spyglass_astronomy.SpyglassAstronomyClient.loadSpace(SpyglassAstronomyClient.java:104)

	at net.minecraft.class_310.handler$ekd000$spyglass_astronomy$loadSpace(class_310.java:23007)

	at net.minecraft.class_310.method_1481(class_310.java:2155)

	at net.minecraft.class_634.method_11117(class_634.java:1114)

	at net.minecraft.class_2724.method_11782(class_2724.java:78)

	at net.minecraft.class_2724.method_11054(class_2724.java:16)

	at net.minecraft.class_2600.method_11072(class_2600.java:22)

	at net.minecraft.class_1255.method_18859(class_1255.java:156)

	at net.minecraft.class_4093.method_18859(class_4093.java:23)

	at net.minecraft.class_1255.method_16075(class_1255.java:130)

 

-- Affected level --

Details:

	All players: 0 total; []

	Chunk stats: 1024, 0

	Level dimension: minecraft:the_nether

	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

	Level time: 0 game time, 0 day time

	Server brand: fabric

	Server type: Non-integrated multiplayer server

Stacktrace:

	at net.minecraft.class_638.method_8538(class_638.java:458)

	at net.minecraft.class_310.method_1587(class_310.java:2406)

	at net.minecraft.class_310.method_1514(class_310.java:826)

	at net.minecraft.client.main.Main.main(Main.java:250)

	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)

	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)

	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

**Comment by BlackFedora1019** [comment] 2024-06-26 22:49
Here is the error message it gives:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_642.method_52811()'

**Comment by KaidKM3** [comment] 2024-06-27 09:35
This is most likely a Duplicate of #25 
This Error is mentioned here too Btw

( I am not the developer but the Author of #25, I am just Letting you know this is most likely a duplicate of #25 because this is the exact same bug experienced there, My question is, When you rejoin, Do you end up in the nether like i do? but if you leave the nether it just crashes again? Then that would answer my question that YES This is a Duplicate of #25)

**Comment by Nettakrim** [comment] 2024-11-07 14:40
closed as its likely a duplicate, iirc i couldnt reproduce #25 but i did do a potential fix for it, but noone has told me if it works or not yet lol, so i wont close #25

**Closed as completed by Nettakrim** 2024-11-07 14:40 UTC
